nav:
  - about: index.md

  - docs: docs.md

  - faq: faq.md

  - getting started:
      - "lessons/getting-started/*.md"
      - demo tour:
          - "tutorials/getting-started/demo-tour/*.md"

  - reference: reference

  - lessons:
    - "lessons/*.md"

  - resources:
      - "resources/*"

  - developer: dev

  - download: https://github.com/odisfm/zcx-core/releases/latest

flatten_single_child_sections: true
