nav:
  - about: index.md

  - docs: docs.md

  - faq: faq.md

  - getting started:
      - "lessons/getting-started/*.md"
      - demo tour:
          - "lessons/getting-started/demo-tour/*.md"

  - reference:
      - "reference/*.md"
      - control reference:
          - "reference/control/*.md"
      - configuration files:
          - "reference/configuration-files/*.md"
      - hardware reference:
          - "reference/hardware/*.md"

  - lessons:
    - "lessons/*.md"

  - resources:
      - "resources/*"

  - developer: dev

  - download: https://github.com/odisfm/zcx-core/releases/latest

flatten_single_child_sections: true
