nav:
  - about: index.md

  - docs: docs.md

  - faq: faq.md

  - getting started:
      - "lessons/getting-started/*.md"
      - demo tour:
          - "lessons/getting-started/demo-tour/*.md"

  - reference:
      - "reference/*.md"
      - control reference:
          - "reference/control/*.md"
      - configuration files:
          - "reference/file/*.md"
      - hardware reference:
          - "reference/hardware/*.md"

  - lessons:
      - "lessons/troubleshooting.md"
      - "lessons/reloading-control-surfaces.md"
      - "lessons/reporting-bugs.md"
      - upgrading: "lessons/upgrade.md"
      - features:
          - "lessons/zcx-user-action.md"
          - session ring: "lessons/session-ring.md"
          - "lessons/session-view.md"
          - "lessons/keyboard.md"
          - "lessons/overlays-layers.md"
          - osc output: "lessons/osc-output.md"
          - "lessons/using-multiple-configs.md"
          - "lessons/custom-banks.md"
      - misc:
          - "lessons/*.md"

  - resources:
      - "resources/*.md"

  - recipes:
      - "recipes/*.md"

  - developer: dev

  - download: https://github.com/odisfm/zcx-core/releases/latest

flatten_single_child_sections: true
