tap_tempo:
  cc: 3

metronome:
  cc: 9

dpad_left:
  cc: 44

dpad_right:
  cc: 45

dpad_up:
  cc: 46

dpad_down:
  cc: 47

select_1:
  cc: 20
  feedback: biled

select_2:
  cc: 21
  feedback: biled

select_3:
  cc: 22
  feedback: biled

select_4:
  cc: 23
  feedback: biled

select_5:
  cc: 24
  feedback: biled

select_6:
  cc: 25
  feedback: biled

select_7:
  cc: 26
  feedback: biled

select_8:
  cc: 27
  feedback: biled

master:
  cc: 28

stop:
  cc: 29

scene_1:
  cc: 43
  feedback: biled

scene_2:
  cc: 42
  feedback: biled

scene_3:
  cc: 41
  feedback: biled

scene_4:
  cc: 40
  feedback: biled

scene_5:
  cc: 39
  feedback: biled

scene_6:
  cc: 38
  feedback: biled

scene_7:
  cc: 37
  feedback: biled

scene_8:
  cc: 36
  feedback: biled

select:
  cc: 48
  stock_modifier: true

shift:
  cc: 49
  stock_modifier: true

note:
  cc: 50

session:
  cc: 51

add_effect:
  cc: 52

add_track:
  cc: 53

octave_down:
  cc: 54

octave_up:
  cc: 55

repeat:
  cc: 56

accent:
  cc: 57

scales:
  cc: 58

mute:
  cc: 60

solo:
  cc: 61
  special_feedback: true

in:
  cc: 62

out:
  cc: 63

duplicate:
  cc: 88

new:
  cc: 87

record:
  cc: 86
  special_feedback: true

play:
  cc: 85
  special_feedback: true

automation:
  cc: 89
  special_feedback: true

fixed_length:
  cc: 90

state_1:
  cc: 102
  feedback: rgb

state_2:
  cc: 103
  feedback: rgb

state_3:
  cc: 104
  feedback: rgb

state_4:
  cc: 105
  feedback: rgb

state_5:
  cc: 106
  feedback: rgb

state_6:
  cc: 107
  feedback: rgb

state_7:
  cc: 108
  feedback: rgb

state_8:
  cc: 109
  feedback: rgb

track:
  cc: 112

clip:
  cc: 113

volume:
  cc: 114

pan_send:
  cc: 115

device:
  cc: 110

browse:
  cc: 111

quantize:
  cc: 116

double:
  cc: 117

delete:
  cc: 118

undo:
  cc: 119
